export const UPDATE_EDIT_DIALOG = 'UPDATE_EDIT_DIALOG';
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';
export const UPDATE_FETCHED_ITEMS = "UPDATE_FETCHED_ITEMS";
export const START_SPINNER = "FETCH_ORDERS_START";
export const STOP_SPINNER = "FETCH_ORDERS_START";
