export const UPDATE_EDIT_DIALOG = 'UPDATE_EDIT_DIALOG';
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';
export const UPDATE_CART_ITEM_EDIT_SIZE = 'UPDATE_CART_ITEM_EDIT_SIZE';
export const UPDATE_CART_ITEM_EDIT_QUANTITY = 'UPDATE_CART_ITEM_EDIT_QUANTITY';
export const UPDATE_FETCHED_ITEMS = "UPDATE_FETCHED_ITEMS";